FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt streamlit

ENV PORT=8501
ENV PYTHONPATH=/app

COPY . .

# Command to run the streamlit app
CMD exec streamlit run frontend/app.py --server.port=$PORT --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false